version: '3.8'

services:
  postgres:
    image: postgres:15.1
    restart: always
    command: postgres -c 'max_connections=1000'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - default
    ports:
      - '5433:5432'

  pgbouncer:
    image: brainsam/pgbouncer:latest
    restart: always
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=1000
    networks:
      - default
    ports:
      - "6432:6432"

  krakend:
    # The :watch image restarts the service automatically when the configuration files change.
    # Do not use this image in production, it's meant to speed up your testing and development.
    image: devopsfaith/krakend:watch
    volumes:
      - ./config/krakend:/etc/krakend
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    command: [ "run", "-d", "-c", "/etc/krakend/krakend.json" ]


networks:
  default:
    driver: bridge

volumes:
  postgresql:
